name: app2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  adaptive_action_sheet: ^2.0.0
  adaptive_theme: ^2.2.0
  animated_splash_screen: ^1.1.0
  cached_network_image: ^3.0.0
  cupertino_icons: null
  cupertino_radio_choice: ^1.0.1+1
  custom_dialog_box: null
  dialog: ^0.7.2+1
  email_validator: ^2.0.1
  file_picker: ^4.0.0
  firebase_analytics: null
  firebase_core:
  firebase_messaging: 10.0.4
  flappy_search_bar: ^1.7.2
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  flutter_local_notifications: null
  flutter_pdfview: ^1.1.0
  flutter_slidable: ^0.6.0
  font_awesome_flutter: null
  get: ^4.1.4
  getwidget: ^1.2.4
  http: ^0.13.3
  image_picker: 0.8.1
  image_viewer: ^1.5.0
  intl: null
  lottie: ^1.0.1
  mime: ^1.0.0
  open_iconic_flutter: ^0.3.0
  path: ^1.7.0
  path_provider: ^2.0.1
  permission_handler: null
  provider: ^5.0.0
  shared_preferences: ^2.0.0
  slider_button: null
  timeago: ^3.0.2
  toast: ^0.1.5
  typicons_flutter: ^0.4.2
  will_tabbar: null

cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  assets:
    - asset/illustration.png
    - asset/logo.png
    - asset/logo2.png
    - asset/image.png
    - asset/newLogo.png
    - asset/newLogowithName.png
    - asset/newLogoWithName2.png
    - asset/newLogo3.png
    - asset/google.png
    - asset/facebook.png
    - asset/github.png

  fonts:
    - family: Gilory
      fonts:
        - asset: asset/fonts/Gilroy-Light.ttf
    - family: GiloryBold
      fonts:
        - asset: asset/fonts/Gilroy-ExtraBold.ttf

    - family: CCL
      fonts:
        - asset: asset/fonts/CascadiaCode-Light.ttf
    - family: CCB
      fonts:
        - asset: asset/fonts/CascadiaCode-Bold.ttf

    - family: RubikL
      fonts:
        - asset: asset/fonts/Rubik-Light.ttf
    - family: RubikB
      fonts:
        - asset: asset/fonts/Rubik-Bold.ttf
